### ISSUE TITLE
Centering of top menus

### ISSUE THREAD

**Issue by Brian393** [edwardsharp/ecotopia-today#12]
The three top menu items are now divided evenly in the top bar. But their should be some padding on left and right, so that they cluster together just a bit. I can adjust whatever initial value is set, but right now I just don't know how to do it.

**Comment by edwardsharp** [comment]
@Brian393 this one doesn't quite make sense to me. where exactly are you wanting some padding?

**Comment by Brian393** [comment]
On the right and left sides so that the menu items are a bit more in the
middle and a bit further from the ends. I don't know if padding is the
right way to do that

**Comment by edwardsharp** [comment]
@Brian393 on the right & left of each item? like outside the nav button item? this would mean we would need to reduce the width of the button. also, this nav is really responsive so it really also depends how wide the user's window is. 

maybe this is something we should pair program together to resolve?

**Comment by Brian393** [comment]
Sorry it's so confusing. Just on the left of Megaregion and the right of
Bioregion. This would make all three of them come nearer to each other. I
think it would look a lot better.

**Comment by Brian393** [comment]
But we can resolve it however you like! I am working now to get the dams
material set up correctly.

**Comment by edwardsharp** [comment]
@Brian393 is this really important? currently the distribution is handled via CSS flex which is really simple because it distributes the space evenly between. we would need to figure out a lot more calculations (and it gets even more cumbersome with the responsive design) to style like you are asking.

**Comment by Brian393** [comment]
Hmm, yes, I understand. Or I think I do. Just to make sure it's clear what
I want, I send two images. If it's difficult or problematic let's leave it
aside and maybe later we can talk about it.

Thanks so much for paying attention to all these things.

**Comment by edwardsharp** [comment]
@Brian393 i pushed a fix for this but it's now causing the page to be too wide in some cases (when the window size is ~850px - 950px)

**Comment by Brian393** [comment]
I noticed you did that and I think it looks great! Can't reproduce the
error. But it's great that you check so closely. Maybe we should leave it
for a moment and see what happens. Could you comment the fix in the file so
I can see where it is?

I should have said this before, but in all these issues, it would be great
to comment in the files so I can see what's involved.

**Comment by edwardsharp** [comment]
@Brian393 so you can just look at my commits to see what i changed. there's even a link to the commit that closed this issue (because i referenced this issue # in my commit message) in this thread. see: "@edwardsharp edwardsharp closed this in 8f64d9c an hour ago". so just click on the link to https://github.com/edwardsharp/ecotopia-today/commit/8f64d9c3317d8a0b5597c3d4aa0d666b4589104c
